//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn_QLCC.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SuDung_LanD {
            get {
                return ((bool)(this["SuDung_LanD"]));
            }
            set {
                this["SuDung_LanD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Block_Keystroke {
            get {
                return ((bool)(this["Block_Keystroke"]));
            }
            set {
                this["Block_Keystroke"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Type_openLog {
            get {
                return ((string)(this["Type_openLog"]));
            }
            set {
                this["Type_openLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Check_Viewlog {
            get {
                return ((bool)(this["Check_Viewlog"]));
            }
            set {
                this["Check_Viewlog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Check_Cancel_HiddenMode {
            get {
                return ((bool)(this["Check_Cancel_HiddenMode"]));
            }
            set {
                this["Check_Cancel_HiddenMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CancelorOK_Hiddenmode {
            get {
                return ((bool)(this["CancelorOK_Hiddenmode"]));
            }
            set {
                this["CancelorOK_Hiddenmode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckShowMessage_Again {
            get {
                return ((bool)(this["CheckShowMessage_Again"]));
            }
            set {
                this["CheckShowMessage_Again"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Strop_Logging_All {
            get {
                return ((bool)(this["Strop_Logging_All"]));
            }
            set {
                this["Strop_Logging_All"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Stop logging")]
        public string Simbutton3_text {
            get {
                return ((string)(this["Simbutton3_text"]));
            }
            set {
                this["Simbutton3_text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool State_checkbox_startup {
            get {
                return ((bool)(this["State_checkbox_startup"]));
            }
            set {
                this["State_checkbox_startup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Your computer is monitered")]
        public string Warning_text {
            get {
                return ((string)(this["Warning_text"]));
            }
            set {
                this["Warning_text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool State_warning_text {
            get {
                return ((bool)(this["State_warning_text"]));
            }
            set {
                this["State_warning_text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Control+A")]
        public string Hot_Key {
            get {
                return ((string)(this["Hot_Key"]));
            }
            set {
                this["Hot_Key"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3/11/2018")]
        public string Self_destruct_date {
            get {
                return ((string)(this["Self_destruct_date"]));
            }
            set {
                this["Self_destruct_date"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Enable_security {
            get {
                return ((bool)(this["Enable_security"]));
            }
            set {
                this["Enable_security"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool First_Security {
            get {
                return ((bool)(this["First_Security"]));
            }
            set {
                this["First_Security"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Security_pass {
            get {
                return ((string)(this["Security_pass"]));
            }
            set {
                this["Security_pass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Protect_log_viewer {
            get {
                return ((bool)(this["Protect_log_viewer"]));
            }
            set {
                this["Protect_log_viewer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Protect_Option_viewer {
            get {
                return ((bool)(this["Protect_Option_viewer"]));
            }
            set {
                this["Protect_Option_viewer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Protect_exit {
            get {
                return ((bool)(this["Protect_exit"]));
            }
            set {
                this["Protect_exit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Protect_hidden_mode {
            get {
                return ((bool)(this["Protect_hidden_mode"]));
            }
            set {
                this["Protect_hidden_mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool first_check_use_pass {
            get {
                return ((bool)(this["first_check_use_pass"]));
            }
            set {
                this["first_check_use_pass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Stop {
            get {
                return ((bool)(this["Stop"]));
            }
            set {
                this["Stop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Enable_keystroke {
            get {
                return ((bool)(this["Enable_keystroke"]));
            }
            set {
                this["Enable_keystroke"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Enable_clipboard {
            get {
                return ((bool)(this["Enable_clipboard"]));
            }
            set {
                this["Enable_clipboard"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Enable_LogApp {
            get {
                return ((bool)(this["Enable_LogApp"]));
            }
            set {
                this["Enable_LogApp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Enable_LogWeb {
            get {
                return ((bool)(this["Enable_LogWeb"]));
            }
            set {
                this["Enable_LogWeb"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Enable_Screenshoot {
            get {
                return ((bool)(this["Enable_Screenshoot"]));
            }
            set {
                this["Enable_Screenshoot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Enable_Webcam {
            get {
                return ((bool)(this["Enable_Webcam"]));
            }
            set {
                this["Enable_Webcam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Stop2 {
            get {
                return ((bool)(this["Stop2"]));
            }
            set {
                this["Stop2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OK_fun {
            get {
                return ((bool)(this["OK_fun"]));
            }
            set {
                this["OK_fun"] = value;
            }
        }
    }
}
